"""Abstract Base Classes for GERT plugins."""

from abc import ABC, abstractmethod
from typing import Any

import pluggy

from gert.updates.base import UpdateAlgorithm


class ForwardModelPlugin(ABC):
    """Abstract base class for GERT forward model step plugins.

    Plugin developers should inherit from this class to strictly define
    the inputs (parameters) they consume and the outputs (responses) they produce.
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """The unique identifier for this forward model."""

    @abstractmethod
    def get_consumed_parameters(
        self,
        arguments: dict[str, str],
    ) -> list[str]:
        """Returns a list of parameter names this step needs access to.÷"""

    @abstractmethod
    def get_expected_responses(
        self,
        arguments: dict[str, Any],
        **kwargs: object,
    ) -> list[str]:
        """Returns a list of response keys generated by this step.

        Returns:
            list[str]: E.g., ["FOPR", "FWPR"]
        """

    @abstractmethod
    def build_command(self, arguments: dict[str, Any], **kwargs: object) -> str:
        """Build the command or execution context to be passed to the queue driver.

        Unlike lifecycle hooks, forward model plugins do not execute
        directly in the main thread. Instead, they generate the necessary
        command(s) for the HPC/job scheduler to run.
        """


class LifecycleHookPlugin(ABC):
    """Abstract base class for GERT lifecycle hooks."""

    @property
    @abstractmethod
    def name(self) -> str:
        """The unique identifier for this hook plugin
        (matches 'uses' in invoking PluginForwardModelStep)."""

    @abstractmethod
    def execute(self, arguments: dict[str, Any], **kwargs: object) -> None:
        """Execute the hook.

        Args:
            arguments (dict[str, Any]): The configuration arguments
            passed via `PluginLifecycleHook` invoking this hook.
            **kwargs: Additional runtime context provided by the GERT engine.
        """


# Used for implementations (Contributor side)
gert_plugin = pluggy.HookimplMarker("gert")


# 2. Define the Hook Specifications (The Contract)
class GertPluginSpecs:
    """GERT hook specifications.

    External contributors will implement these functions to register their plugins.
    """

    @pluggy.HookspecMarker("gert")
    def gert_forward_model_steps(self) -> list[ForwardModelPlugin]:
        """Discover and load external forward model step plugins."""
        return []

    @pluggy.HookspecMarker("gert")
    def gert_lifecycle_hooks(self) -> list[LifecycleHookPlugin]:
        """Discovers and returns a list of installed lifecycle hook plugins."""
        return []

    @pluggy.HookspecMarker("gert")
    def gert_update_algorithms(self) -> list[UpdateAlgorithm]:
        """Discover and load external update algorithm plugins."""
        return []


# 3. Create the Plugin Manager Factory
def get_plugin_manager() -> pluggy.PluginManager:
    pm = pluggy.PluginManager("gert")

    # Register our hook specifications
    pm.add_hookspecs(GertPluginSpecs)

    # Automatically discover plugins registered via setuptools entry points
    pm.load_setuptools_entrypoints("gert")

    return pm


# 4. Convenient Runtime Wrapper
class GertRuntimePlugins:
    """The main interface for GERT to interact with installed plugins.

    This class gathers all distributed plugins once and provides easy
    access to them via lists or lookup maps.
    """

    def __init__(self) -> None:
        self._pm = get_plugin_manager()
        self.forward_model_steps = self._get_forward_model_steps_from_plugin_manager()
        self.lifecycle_hooks = self._get_lifecycle_hooks_from_plugin_manager()
        self.update_algorithms = self._get_update_algorithms_from_plugin_manager()

    def _get_forward_model_steps_from_plugin_manager(self) -> list[ForwardModelPlugin]:
        """Wraps the pluggy hook call and flattens the results into a single list."""
        raw_results = self._pm.hook.gert_forward_model_steps() or []
        return [item for sublist in raw_results for item in sublist]

    def _get_lifecycle_hooks_from_plugin_manager(self) -> list[LifecycleHookPlugin]:
        """Wraps the pluggy hook call and flattens the results into a single list."""
        raw_results = self._pm.hook.gert_lifecycle_hooks() or []
        return [item for sublist in raw_results for item in sublist]

    def _get_update_algorithms_from_plugin_manager(self) -> list[UpdateAlgorithm]:
        """Wraps the pluggy hook call and flattens the results into a single list."""
        raw_results = self._pm.hook.gert_update_algorithms() or []
        return [item for sublist in raw_results for item in sublist]
